### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: ///)/: Unmatched ')'

### ISSUE THREAD

**Issue by cptSwing** [olafklingt/fold-whatever#10]
[Enter steps to reproduce:]

1. Enter Reg Ex pattern `(\/\/)/g` (I am attempting to fold away comments)
2. Profit!

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: [fold-whatever](https://github.com/olafklingt/fold-whatever) package 0.2.4

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /\/)/: Unmatched ')'

```
At C:\Users\ph4tt\.atom\packages\fold-whatever\lib\fold-whatever.js:109

SyntaxError: Invalid regular expression: /\/)/: Unmatched ')'
    at new RegExp (<anonymous>)
    at Object.foldAll (/packages/fold-whatever/lib/fold-whatever.js:109:15)
    at Object.toggleAll (/packages/fold-whatever/lib/fold-whatever.js:228:12)
    at HTMLElement.foldWhateverToggleAll (/packages/fold-whatever/lib/fold-whatever.js:49:48)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:350017)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1212945)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1209079)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:285196)
```

### Commands

```
     -0:07.9.0 fold-whatever:toggle-all (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.0 
color-picker 2.3.0 
css-snippets 1.1.0 
dracula-syntax 2.0.7 
dracula-ui 0.6.0 
emmet 2.4.3 
es6-snippets 0.3.0 
file-icons 2.1.27 
fold-lines 0.2.2 
fold-whatever 0.2.4 
gl-light-syntax 3.0.0 
gloom 0.6.5 
intentions 1.1.5 
language-babel 2.85.0 
linter 2.3.0 
linter-csslint 2.0.2 
linter-htmllint 1.0.1 
linter-jshint 3.1.9 
linter-ui-default 1.7.1 
pigments 0.40.2 
script 3.18.1 
sepia-light-ui 0.5.0 
sepia-syntax 1.1.0 
sort-lines 0.18.0 
sync-settings 0.8.6 
```

**Comment by olafklingt** [comment]
Your regex is not well thought through. I think you simply missing a / at the beginning of the regex but it will not match more than the two //.
Sorry I can not debug regexes here.

**Comment by cptSwing** [comment]
Hey thanks for the reply - that's very well possible, I am not having the best time trying to wrap my beginner head around RegEx. However, the same regex works fine here: https://regex101.com/r/rKLKB2/2

EDIT: Feel free to ignore me. Am now using this `/\/\*[\s\S]*?\*\/|([^\\:]|^)\/\/.*$/gm` and it works like a charm. Sorry for opening an issue and thanks for the Atom package!

**Comment by olafklingt** [comment]
Did you try my suggestion? 
And does the website uses the same regex engine as atom? 
The regex also on the website doesn't match comments.

**Comment by olafklingt** [comment]
Cool that you found the right regex.
